// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Cross-reference table mapping stores, vendors, and employees to people
    /// </summary>
    [Table("BusinessEntityContact", Schema = "Person")]
    [Index(nameof(rowguid), Name = "AK_BusinessEntityContact_rowguid", IsUnique = true)]
    [Index(nameof(ContactTypeID), Name = "IX_BusinessEntityContact_ContactTypeID")]
    [Index(nameof(PersonID), Name = "IX_BusinessEntityContact_PersonID")]
    public partial class BusinessEntityContact
    {
        /// <summary>
        /// Primary key. Foreign key to BusinessEntity.BusinessEntityID.
        /// </summary>
        [Key]
        public int BusinessEntityID { get; set; }
        /// <summary>
        /// Primary key. Foreign key to Person.BusinessEntityID.
        /// </summary>
        [Key]
        public int PersonID { get; set; }
        /// <summary>
        /// Primary key.  Foreign key to ContactType.ContactTypeID.
        /// </summary>
        [Key]
        public int ContactTypeID { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(BusinessEntityID))]
        [InverseProperty("BusinessEntityContacts")]
        public virtual BusinessEntity BusinessEntity { get; set; }
        [ForeignKey(nameof(ContactTypeID))]
        [InverseProperty("BusinessEntityContacts")]
        public virtual ContactType ContactType { get; set; }
        [ForeignKey(nameof(PersonID))]
        [InverseProperty("BusinessEntityContacts")]
        public virtual Person Person { get; set; }
    }
}