// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Lookup table containing the types of business entity contacts.
    /// </summary>
    [Table("ContactType", Schema = "Person")]
    [Index(nameof(Name), Name = "AK_ContactType_Name", IsUnique = true)]
    public partial class ContactType
    {
        public ContactType()
        {
            BusinessEntityContacts = new HashSet<BusinessEntityContact>();
        }

        /// <summary>
        /// Primary key for ContactType records.
        /// </summary>
        [Key]
        public int ContactTypeID { get; set; }
        /// <summary>
        /// Contact type description.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [InverseProperty(nameof(BusinessEntityContact.ContactType))]
        public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
    }
}