// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Product subcategories. See ProductCategory table.
    /// </summary>
    [Table("ProductSubcategory", Schema = "Production")]
    [Index(nameof(Name), Name = "AK_ProductSubcategory_Name", IsUnique = true)]
    [Index(nameof(rowguid), Name = "AK_ProductSubcategory_rowguid", IsUnique = true)]
    public partial class ProductSubcategory
    {
        public ProductSubcategory()
        {
            Products = new HashSet<Product>();
        }

        /// <summary>
        /// Primary key for ProductSubcategory records.
        /// </summary>
        [Key]
        public int ProductSubcategoryID { get; set; }
        /// <summary>
        /// Product category identification number. Foreign key to ProductCategory.ProductCategoryID.
        /// </summary>
        public int ProductCategoryID { get; set; }
        /// <summary>
        /// Subcategory description.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(ProductCategoryID))]
        [InverseProperty("ProductSubcategories")]
        public virtual ProductCategory ProductCategory { get; set; }
        [InverseProperty(nameof(Product.ProductSubcategory))]
        public virtual ICollection<Product> Products { get; set; }
    }
}