// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Changes in the cost of a product over time.
    /// </summary>
    [Table("ProductCostHistory", Schema = "Production")]
    public partial class ProductCostHistory
    {
        /// <summary>
        /// Product identification number. Foreign key to Product.ProductID
        /// </summary>
        [Key]
        public int ProductID { get; set; }
        /// <summary>
        /// Product cost start date.
        /// </summary>
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// Product cost end date.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// Standard cost of the product.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal StandardCost { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(ProductID))]
        [InverseProperty("ProductCostHistories")]
        public virtual Product Product { get; set; }
    }
}