// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Product inventory information.
    /// </summary>
    [Table("ProductInventory", Schema = "Production")]
    public partial class ProductInventory
    {
        /// <summary>
        /// Product identification number. Foreign key to Product.ProductID.
        /// </summary>
        [Key]
        public int ProductID { get; set; }
        /// <summary>
        /// Inventory location identification number. Foreign key to Location.LocationID. 
        /// </summary>
        [Key]
        public short LocationID { get; set; }
        /// <summary>
        /// Storage compartment within an inventory location.
        /// </summary>
        [Required]
        [StringLength(10)]
        public string Shelf { get; set; }
        /// <summary>
        /// Storage container on a shelf in an inventory location.
        /// </summary>
        public byte Bin { get; set; }
        /// <summary>
        /// Quantity of products in the inventory location.
        /// </summary>
        public short Quantity { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(LocationID))]
        [InverseProperty("ProductInventories")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(ProductID))]
        [InverseProperty("ProductInventories")]
        public virtual Product Product { get; set; }
    }
}