// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Individual products associated with a specific purchase order. See PurchaseOrderHeader.
    /// </summary>
    [Table("PurchaseOrderDetail", Schema = "Purchasing")]
    [Index(nameof(ProductID), Name = "IX_PurchaseOrderDetail_ProductID")]
    public partial class PurchaseOrderDetail
    {
        /// <summary>
        /// Primary key. Foreign key to PurchaseOrderHeader.PurchaseOrderID.
        /// </summary>
        [Key]
        public int PurchaseOrderID { get; set; }
        /// <summary>
        /// Primary key. One line number per purchased product.
        /// </summary>
        [Key]
        public int PurchaseOrderDetailID { get; set; }
        /// <summary>
        /// Date the product is expected to be received.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime DueDate { get; set; }
        /// <summary>
        /// Quantity ordered.
        /// </summary>
        public short OrderQty { get; set; }
        /// <summary>
        /// Product identification number. Foreign key to Product.ProductID.
        /// </summary>
        public int ProductID { get; set; }
        /// <summary>
        /// Vendor&apos;s selling price of a single product.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }
        /// <summary>
        /// Per product subtotal. Computed as OrderQty * UnitPrice.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal LineTotal { get; set; }
        /// <summary>
        /// Quantity actually received from the vendor.
        /// </summary>
        [Column(TypeName = "decimal(8, 2)")]
        public decimal ReceivedQty { get; set; }
        /// <summary>
        /// Quantity rejected during inspection.
        /// </summary>
        [Column(TypeName = "decimal(8, 2)")]
        public decimal RejectedQty { get; set; }
        /// <summary>
        /// Quantity accepted into inventory. Computed as ReceivedQty - RejectedQty.
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal StockedQty { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(ProductID))]
        [InverseProperty("PurchaseOrderDetails")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(PurchaseOrderID))]
        [InverseProperty(nameof(PurchaseOrderHeader.PurchaseOrderDetails))]
        public virtual PurchaseOrderHeader PurchaseOrder { get; set; }
    }
}