// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Sales territory lookup table.
    /// </summary>
    [Table("SalesTerritory", Schema = "Sales")]
    [Index(nameof(Name), Name = "AK_SalesTerritory_Name", IsUnique = true)]
    [Index(nameof(rowguid), Name = "AK_SalesTerritory_rowguid", IsUnique = true)]
    public partial class SalesTerritory
    {
        public SalesTerritory()
        {
            Customers = new HashSet<Customer>();
            SalesOrderHeaders = new HashSet<SalesOrderHeader>();
            SalesPersons = new HashSet<SalesPerson>();
            SalesTerritoryHistories = new HashSet<SalesTerritoryHistory>();
            StateProvinces = new HashSet<StateProvince>();
        }

        /// <summary>
        /// Primary key for SalesTerritory records.
        /// </summary>
        [Key]
        public int TerritoryID { get; set; }
        /// <summary>
        /// Sales territory description
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. 
        /// </summary>
        [Required]
        [StringLength(3)]
        public string CountryRegionCode { get; set; }
        /// <summary>
        /// Geographic area to which the sales territory belong.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Group { get; set; }
        /// <summary>
        /// Sales in the territory year to date.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal SalesYTD { get; set; }
        /// <summary>
        /// Sales in the territory the previous year.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal SalesLastYear { get; set; }
        /// <summary>
        /// Business costs in the territory year to date.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal CostYTD { get; set; }
        /// <summary>
        /// Business costs in the territory the previous year.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal CostLastYear { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [ForeignKey(nameof(CountryRegionCode))]
        [InverseProperty(nameof(CountryRegion.SalesTerritories))]
        public virtual CountryRegion CountryRegionCodeNavigation { get; set; }
        [InverseProperty(nameof(Customer.Territory))]
        public virtual ICollection<Customer> Customers { get; set; }
        [InverseProperty(nameof(SalesOrderHeader.Territory))]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
        [InverseProperty(nameof(SalesPerson.Territory))]
        public virtual ICollection<SalesPerson> SalesPersons { get; set; }
        [InverseProperty(nameof(SalesTerritoryHistory.Territory))]
        public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; }
        [InverseProperty(nameof(StateProvince.Territory))]
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
    }
}