// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Shipping company lookup table.
    /// </summary>
    [Table("ShipMethod", Schema = "Purchasing")]
    [Index(nameof(Name), Name = "AK_ShipMethod_Name", IsUnique = true)]
    [Index(nameof(rowguid), Name = "AK_ShipMethod_rowguid", IsUnique = true)]
    public partial class ShipMethod
    {
        public ShipMethod()
        {
            PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        }

        /// <summary>
        /// Primary key for ShipMethod records.
        /// </summary>
        [Key]
        public int ShipMethodID { get; set; }
        /// <summary>
        /// Shipping company name.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// Minimum shipping charge.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ShipBase { get; set; }
        /// <summary>
        /// Shipping charge per pound.
        /// </summary>
        [Column(TypeName = "money")]
        public decimal ShipRate { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [InverseProperty(nameof(PurchaseOrderHeader.ShipMethod))]
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        [InverseProperty(nameof(SalesOrderHeader.ShipMethod))]
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    }
}