// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OdataFluentUI.Data.Models
{
    /// <summary>
    /// Sale discounts lookup table.
    /// </summary>
    [Table("SpecialOffer", Schema = "Sales")]
    [Index(nameof(rowguid), Name = "AK_SpecialOffer_rowguid", IsUnique = true)]
    public partial class SpecialOffer
    {
        public SpecialOffer()
        {
            SpecialOfferProducts = new HashSet<SpecialOfferProduct>();
        }

        /// <summary>
        /// Primary key for SpecialOffer records.
        /// </summary>
        [Key]
        public int SpecialOfferID { get; set; }
        /// <summary>
        /// Discount description.
        /// </summary>
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
        /// <summary>
        /// Discount precentage.
        /// </summary>
        [Column(TypeName = "smallmoney")]
        public decimal DiscountPct { get; set; }
        /// <summary>
        /// Discount type category.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        /// <summary>
        /// Group the discount applies to such as Reseller or Customer.
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Category { get; set; }
        /// <summary>
        /// Discount start date.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// Discount end date.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        /// <summary>
        /// Minimum discount percent allowed.
        /// </summary>
        public int MinQty { get; set; }
        /// <summary>
        /// Maximum discount percent allowed.
        /// </summary>
        public int? MaxQty { get; set; }
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid rowguid { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ModifiedDate { get; set; }

        [InverseProperty(nameof(SpecialOfferProduct.SpecialOffer))]
        public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }
    }
}